### ISSUE TITLE
Problem about the backward loss and the forward loss training on surrogate models

### ISSUE THREAD

**Issue by Samaritan-Infi** [TrustworthyDL/LeBA#2]
Hello, yang:

Thanks for your impressive work of LeBA.

I am wondering have you tested train the surrogate models with the forward loss and backward loss separately, which means that I use several clean images to train with the forward loss, then during the attacking process with the backward loss. Will that work? 
In the code, the FL_rate is set to control the loss. On the above way, how do I set the updated rate?

Yours!
Fei.

**Comment by duducheng** [comment]
Hi @Samaritan-Infi,

Please refer to Table 5 on Forward Loss and Backward Loss performance.

**Comment by duducheng** [comment]
Oh sorry @Samaritan-Infi , I seem to misunderstood your question at my first glance. 

We have not tested the setting that you described, as we are interested in the query efficiency to improve our SimBA++ baseline; We would like to use each query feedback at highest efficiency. 

I suggest you may test this setting by your own. Good luck!

Jiancheng
